### ISSUE TITLE
Need a way to override the function that generates the file name.

### ISSUE THREAD

**Issue by dumptyd** [maxcountryman/flask-uploads#12]
I can't find anything related to this in the docs except this:

>The default implementation splits the name and extension and adds a suffix to the name consisting of an underscore and a number, and tries that until it finds one that doesn’t exist. 

under `resolve_conflict` section.

. Is there a way to do this?

**Comment by shuttle1987** [comment]
You can subclass `UploadSet` and implement your own `resolve_conflict` method. Also you could monkeypatch if you needed. This is something that I would also like to see a better way of dealing with and would be willing to invest the time to write.

**Comment by spiropan** [comment]
Hi,
Can you please elaborate a bit on your proposed sub-classing solution? Is there also any way to easily switch off resolving conflicts altogether (i.e. just overwrite the original file)?
Thanks!

**Comment by vueee** [comment]
hi,
For my opinion,  you should rename the old one, and keep the new one's name.
Like user update their profile photo.
At least should have choice in CONFIG if user want overwrite the original file rather than rename it.

**Comment by maxcountryman** [comment]
Please use StackOverflow for questions about how to use the library.
