### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by nitrocode** [maxcountryman/flask-uploads#16]
@maxcountryman  First, Thank you for the excellent plugin.

I was planning to use this extension instead of rolling out my own but I noticed numerous open PRs and open issues. Is this repo still maintained?

**Comment by maxcountryman** [comment]
Hi, the plugin is maintained although I haven’t had the time to merge in many PRs lately. If you need a release we can arrange that otherwise you can always pin a git sha.

**Comment by nitrocode** [comment]
No worries, I'll use it instead of writing my own then! Thank you for the quick response
