### ISSUE TITLE
Can't use any filetype preset other IMAGES

### ISSUE THREAD

**Issue by ghost** [maxcountryman/flask-uploads#17]
Versions:
click            6.7    
Flask            0.12.1 
Flask-Autodoc    0.1.2  
Flask-HTTPAuth   3.2.3  
Flask-SQLAlchemy 2.2    
Flask-Uploads    0.2.1  
itsdangerous     0.24   
Jinja2           2.9.6  
MarkupSafe       1.0    
passlib          1.7.1  
Pillow           5.1.0  
pip              10.0.1 
pkg-resources    0.0.0  
psycopg2         2.7.4  
psycopg2-binary  2.7.4  
setuptools       39.0.1 
SQLAlchemy       1.1.11 
Werkzeug         0.12.2 
wheel            0.31.0 

With IMAGES:
`app.config['UPLOADED_ACTIMG_ALLOW'] = 'IMAGES'
app.config['UPLOADED_ACTIMG_DEST'] = '/home/flask/ADB/test_02/actimg'
app.config['UPLOADED_EXTIMG_DEST'] = '/home/flask/ADB/test_02/extimg'
db = SQLAlchemy(app)
auth = HTTPBasicAuth()

act_img = UploadSet('actimg')
ext_img = UploadSet('extimg')
configure_uploads(app, (act_img, ext_img))
`
`10.0.0.141 - - [10/May/2018 20:59:16] "POST /api/activity/set_img HTTP/1.1" 201 -`

WITH ALL:
`app.config['UPLOADED_ACTIMG_ALLOW'] = 'ALL'
app.config['UPLOADED_ACTIMG_DEST'] = '/home/flask/ADB/test_02/actimg'
app.config['UPLOADED_EXTIMG_DEST'] = '/home/flask/ADB/test_02/extimg'
db = SQLAlchemy(app)
auth = HTTPBasicAuth()

act_img = UploadSet('actimg')
ext_img = UploadSet('extimg')
configure_uploads(app, (act_img, ext_img))`

` 
File "/home/flask/ADB/test_02/venv/lib/python3.5/site-packages/flask_uploads.py", line 415, in save                                                                                                              
    raise UploadNotAllowed()                                                                                                                                                                                       
flask_uploads.UploadNotAllowed                                                                                                                                                                                     
10.0.0.141 - - [10/May/2018 21:02:06] "POST /api/bill/set_img HTTP/1.1" 500 - 
`

**Comment by maxcountryman** [comment]
Please use StackOverflow for questions about how to use the library.
