### ISSUE TITLE
A question for UploadSet.save()

### ISSUE THREAD

**Issue by RicardoScofileld** [maxcountryman/flask-uploads#21]
When I use UploadSet instance save to file, It's raise UploadNotAllowed Exception. I find it strange，so, I read your code. finally, I found it, Because I'm Chinese, the filename maybe is Chinese. But, when the filename is Chinese, use the werkzeug.secure_filename(), the result is the extension. For example. 
`filename = 'boy.jpg'`
`res = secure_filename(filename)`
res is boy.jpg, but when the filename is chinese
`filename = '男孩.jpg'`
`res = secure_filename(filename)`
res is jpg.

**Comment by maxcountryman** [comment]
Please use StackOverflow for questions about how to use the library.
