### ISSUE TITLE
Package and tests are broken since release of Werkzeug 1.0.0

### ISSUE THREAD

**Issue by jugmac00** [maxcountryman/flask-uploads#29]
Werkzeug has moved some long deprecated functions/Classes to separate modules.

Since the release of Werkzeug 1.0.0 this package here is broken, also the tests do not work any more.

I created #28 to fix the broken imports.

Could you please cut a new release after merging the PR?

Thanks a lot!  

P.S.: If you activate Travis for this repository, I'd volunteer to create a config file and do some minor housekeeping.

**Comment by andresgarita-dev** [comment]
Same problem in from werkzeug import secure_filename, FileStorage
should be from werkzeug.utils

**Comment by jugmac00** [comment]
@maxcountryman @rduplain 
Thank you for accepting the pull request. Could you please cut a new release?
While it is possible to directly install from GitHub, it is quite cumbersome to configure `setup.py` with `dependency_links`.
Thank you very much!

**Comment by jugmac00** [comment]
It is not only cumbersome, it seems no longer possible:
https://github.com/pypa/setuptools/issues/987#issuecomment-524576244

**Comment by jugmac00** [comment]
As a workaround you can use something like
```   "Flask-Uploads @ https://github.com/maxcountryman/flask-uploads/archive/f66d7dc93e684fa0a3a4350a38e41ae00483a796.zip#egg=Flask-Uploads-0.2.2.dev",  # noqa: E501```
in your `setup.py`.

**Attention**
This fails on Travis for Python 3.6.

**Comment by Frost199** [comment]
I had to downgrade to `werkzeug==0.16.0` to get it working with Flask-Uploads, everything just breaks as of the release of `werkzeug==1.0.0` 😢 , most things have been moved to different packages within werkzeug. It would be nice if Flask-Upload can update its library.

**Comment by maxcountryman** [comment]
Pull requests are welcome.

**Comment by Curiouspaul1** [comment]
I thought is was the only one seeing this.: cannot import name 'secure_filename' from 'werkzeug' (/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/werkzeug/__init__.py) #98
pheww.. thought i'd screwed things up for a minute..may i ask though (WHAT's the way forward)

**Comment by jugmac00** [comment]
@maxcountryman #28 was the PR - which you already merged. But it would be very good to have a new release out there.

While you technically can pip install from a GitHub URL, it is a major pain to have a GitHub URL in a `setup.py` supporting different Python versions (`dependency_links` vs `install_requires`).

**Comment by maxcountryman** [comment]
Why is using a link a major pain? I’ve done this for many projects and it’s never been much of a hassle.

**Comment by jugmac00** [comment]
At least I could not find a way to run the tests of my applications successfully on Py36-Py38 with a GitHub URL in my setup.py (on Travis only - locally it worked out):

```
Direct url requirement (like Flask-Uploads@ https://github.com/maxcountryman/flask-uploads/archive/f66d7dc93e684fa0a3a4350a38e41ae00483a796.zip#egg=Flask-Uploads-0.2.2.dev) are not allowed for dependencies
```

And I tried for a bit :-)

![Screenshot from 2020-02-16 21-11-41](https://user-images.githubusercontent.com/9895620/74611968-21140a00-5101-11ea-9280-4102f384b9a1.png)

What is the issue with cutting a release? Should not take more than a couple of minutes and would make the life of your users much easier.

I finally dropped Py3.6 - and so I am personally fine. So I am not asking for myself.

Is there anything I could do to support you?

**Comment by shaharyi** [comment]
I also upgraded to flask 1.1.1 with Werkzeug 1.0 and got the deprecate imports.
(I wanted to use Python3.7 dataclasses module for json serialization)
I'd be grateful for a release soon if possible, please.

**Comment by sgreene570** [comment]
> Why is using a link a major pain? I’ve done this for many projects and it’s never been much of a hassle.

I see your point, but honestly it's just inconvenient. Also, even if a url replacement is a quick fix, that's still manual intervention that folks would have to figure out when their builds break. I am very much in favor of a new release to fix the issue and would also be willing to help with any testing or logistics for that :smile: :rocket:

**Comment by jgerry2002** [comment]
What exactly is holding up a new release? Latest 0.2.1 still has legacy werkzeug issue. This seems like a trivial fix vs forcing folks to patch an otherwise excellent library.

**Comment by colidyre** [comment]
> I had to downgrade to `werkzeug==0.16.0` to get it working with Flask-Uploads, everything just breaks as of the release of `werkzeug==1.0.0` cry , most things have been moved to different packages within werkzeug. It would be nice if Flask-Upload can update its library.

Why not using the newer `werkzeug==0.16.1`? It is the last version before 1.0.0. This works for me.

**Comment by lesliewubbel** [comment]
can someone fix this issue already?

**Comment by Pythonian** [comment]
> can someone fix this issue already?

This issue was reported since Feb 6, unfortunately, 2 months after, no fix has been applied.

My app is broken.

Please what's holding the maintainers back from fixing this issue? Or are they no longer making use of this extension?

**Comment by Pythonian** [comment]
> can someone fix this issue already?

This issue was reported since Feb 6, unfortunately, 2 months after, no fix has been applied.

My app is broken.

Please what's holding the maintainers back from fixing this issue? Or are they no longer making use of this extension?

**Comment by xxxpsyduck** [comment]
You guys are so F**king lazy! just a simple command: 
`pip install git+https://github.com/maxcountryman/flask-uploads.git`

**Comment by Frost199** [comment]
> You guys are so F**king lazy! just a simple command:
> `pip install git+https://github.com/maxcountryman/flask-uploads.git`

First, a pull request was sent and he merged the PR which is why your pip install from a git repo would work and not break, @maxcountryman is maintaining the library, you should not go about saying people are lazy if they want the merged PR to be updated with a new release.

And being an asshole while letting people know how to pip install from a GitHub repo doesn't make you superman or know it all, I wonder how you collaborate with teams, and @maxcountryman should have closed this issue a long time, you won't come here hiding behind your keyboard and calling people **F@@ing Lazy**.

Next time learn how to be civil about what's not yours and enlighten people properly.

**Comment by sgreene570** [comment]
> You guys are so F**king lazy! just a simple command:
> `pip install git+https://github.com/maxcountryman/flask-uploads.git`

Cutting a new release is a few clicks, no?

**Comment by maxcountryman** [comment]
This isn’t the right forum for this. Everyone, please be civil—also I’d ask that you all remember that open source work is not necessarily paid work: myself and the other maintainers are donating our time without direct monetary compensation. Regardless of how much effort it is or isn’t it’s incredibly rude to demand anyone to do anything on your behalf.
