### ISSUE TITLE
Remove Module from imports

### ISSUE THREAD

**Issue by gledi** [maxcountryman/flask-uploads#3]
I updated a project of mine to Flask 0.11 and I noticed that I could not start the development server. It failed with the following error:

```
ImportError: cannot import name 'Module'
```

and it was due to this line in `flask_uploads.py`:

``` python
from flask import current_app, Module, send_from_directory, abort, url_for
```

`Module` has been deprecated for a long time now and apparently has been removed completely in 0.11. As far as I can see you are not making use of that anywhere and by just removing it I can run the application just fine.

Please consider removing this unused import since it seems like it's a really minor fix.

**Comment by starplanet** [comment]
+1

**Comment by gledi** [comment]
I see that `Module` was removed with #4. Do you have any plan to push a new release to PyPi? Sorry to bother you about this and if it takes too much of your time or does not make sense to release a new version for such a small change I totally understand.
All the best

**Comment by Tomazz** [comment]
+1
