### ISSUE TITLE
upload return url is not working when I am saving the pic in multiples destination

### ISSUE THREAD

**Issue by Subhanan1986** [maxcountryman/flask-uploads#34]
I am using flask dropzone along with flask_uploads. 
here is my upload func
`@current_user_dashboard_view.route('/upload_post_photo', methods=['POST'])
@login_required
def upload_post_photo():
    current_app.config['UPLOADED_PHOTOS_DEST'] = os.getcwd() + '/static/assets/users_assets/' + str(
        current_user.id)
    photos = UploadSet('photos', IMAGES)
    configure_uploads(current_app, photos)
    patch_request_class(current_app)
    if "file_urls" not in session:
        session['file_urls'] = []
    file_urls = session['file_urls']
    if request.method == 'POST':
        file_obj = request.files
        if file_obj is None:
            print('File obj is none')
        for f in file_obj:
            file = request.files.get(f)
            filename = photos.save(
                file,
                name=file.filename
            )
            file_urls.append(photos.url(filename))
        session['file_urls'] = file_urls
        return 'Pic is uploading'
    return 'Pic is uploading'`

I have initialize the upload in my init file and overriding it in upload_post_photo route. cause I want to store the image based on logged in user folder. photos are storing correctly and using the session variable I am storing it in my database.  
sample pic access url
http://127.0.0.1:5001/_uploads/photos/mlogo_1.png

but when I am trying to view it sometime the this access url doesn't work sporadically. 

note : I have save the content in a single folder this issue is not happening. not sure what is happening

**Comment by maxcountryman** [comment]
Please use StackOverflow for questions about how to use the library.
