### ISSUE TITLE
Unique filename feature?

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [maxcountryman/flask-uploads#40]
Let's say i have

```python
# alldocs = UploadSet('alldocs', DOCUMENTS)
alldocs.save(request.files[form.file_input.data.name])
```
as adapted from [here](http://www.patricksoftwareblog.com/tag/flask-uploads/) under Updating The Route.

Now i want each filename to be unique. If i try to add some random chars at the beginning:

```python
alldocs.save(rand_func() + '_' + request.files[form.file_input.data.name])
# to get like werugt387tgr36_file.pdf
```

it says:

```
TypeError: storage must be a werkzeug.FileStorage
```

Maybe there should be an easy way to have unique filename?

**Comment by jugmac00** [comment]
Hi @Abdur-rahmaanJ 

when you have a look at the source code

https://github.com/maxcountryman/flask-uploads/blob/f66d7dc93e684fa0a3a4350a38e41ae00483a796/flask_uploads.py#L460-L479

you'll see, that you do not have to take care of this problem yourself. It is automatically made sure that filenames are unique.

In some other closed issues I read that the maintainer of this package here prefers that questions do not go into tickets, but should be asked on StackOverflow.

Maybe it would be a good idea if this was put in the README.

**Comment by Abdur-rahmaanJ** [comment]
Ok let me just add a note PR in  the README. And rephrase the issue as filename customisation.

**Comment by Abdur-rahmaanJ** [comment]
Seems readme bit desert, will do in docs.
