### ISSUE TITLE
When 0.2.2?

### ISSUE THREAD

**Issue by murbard** [maxcountryman/flask-uploads#41]
The latest version on pypi is still 0.2.1 which doesn't get the import from werkzeug right. This does not seem to be an issue in the master branch. It would be convenient if this were released as a new version.

**Comment by jugmac00** [comment]
The maintainer does not want to create manual releases for this package here, but offers a way to get releases via GitHub actions (#39).

You could also use `Flask-Reuploaded` as a drop-in replacement - see https://github.com/jugmac00/flask-reuploaded

**Comment by murbard** [comment]
Ah thanks, missed this.
