### ISSUE TITLE
A reasonable way to handle with different upload_path and serve_path

### ISSUE THREAD

**Issue by TennyZhuang** [maxcountryman/flask-uploads#7]
The project structure

```
app/
  __init__.py
config.py
manage.py
```

I create an UploadSet in `app/__init__.py`

``` python
photos = UploadSet('photos', IMAGES)
```

When I set `UPLOADS_DEFAULT_DEST = 'app/uploads/'`, the photos will save at `app/uploads`

but when I visit `http://localhost/_uploads/photos/bg.jpg`, 

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tianyizhuang/Projects/CamusKit.Backend/app/app/uploads/photos/bg.jpg'
```

An extra `app` in the path.

What's the reasonable way to deal with the problem?

**Comment by tjcim** [comment]
Use the builtin function `photos.url("bg.jpg")` to get the URL for the image.

**Comment by maxcountryman** [comment]
Please use StackOverflow for questions about how to use the library.
